Repository 2024-Summer-BootCamp-TeamK/Backend, pull requests merged in 2024-07, with the labels that each got.

#11 Feat/#5 계약서 검토 업로드
  .DS_Store
  myproject/contracts/migrations/0001_initial.py
  myproject/contracts/models.py
  myproject/contracts/uploadurls.py
  myproject/contracts/uploadviews.py
  myproject/contracts/utils.py
  myproject/myproject/settings.py
  myproject/myproject/urls.py
Labels: 기능구현

#15 refactor : swagger 문서 구체화
  myproject/contracts/uploadviews.py
  myproject/contracts/utils.py
  requirements.txt
Labels: 리팩토링

#18 [feat/#18] 파일 조회
  myproject/documents/models.py
  myproject/documents/serializers.py
  myproject/documents/urls.py
  myproject/documents/views.py
  myproject/myproject/settings.py
Labels: 기능구현

#21 [Feat/#20] 무작위 비밀번호 생성 및 공유 페이지 접근 API 구현 완료
  myproject/documents/urls.py
  myproject/documents/utils.py
  myproject/documents/views.py
  myproject/myproject/urls.py
Labels: 기능구현

#23 Feat/#16
  .DS_Store
  myproject/.DS_Store
  myproject/contracts/.DS_Store
  myproject/contracts/migrations/0002_type_article_type.py
  myproject/contracts/migrations/0003_alter_article_law.py
  myproject/contracts/models.py
  myproject/contracts/uploadSerializers.py
  myproject/contracts/uploadurls.py
  myproject/contracts/uploadviews.py
  myproject/contracts/utils/openai_call.py
  myproject/contracts/utils/pdf_to_html.py
  myproject/contracts/utils/prompts.py
  requirements.txt
Labels: 기능구현

#29 [Feat/#8] 원본PDF 수정 PDF로 변경
  myproject/documents/urls.py
  myproject/documents/views.py
  myproject/myproject/urls.py
Labels: 기능구현

#37 Issue/#36 GPT JSON 키값 누락 해결
  myproject/contracts/checkViews.py
  myproject/contracts/utils/prompts.py
  myproject/documents/urls.py
Labels: 오류수정

#44 refactor/#41 비동기 처리
  myproject/documents/tasks.py
  myproject/documents/views.py
  myproject/myproject/celery.py
  myproject/myproject/settings.py
Labels: 리팩토링

#46 [Feat/#43] 계약서 공유 소켓 통신 연결 완료
  myproject/documents/consumers.py
  myproject/documents/routing.py
  myproject/myproject/routing.py
  myproject/myproject/settings.py
Labels: 기능구현, 환경설정

#49 Feat/#42 검토결과 main API 구현
  .DS_Store
  myproject/.DS_Store
  myproject/contracts/.DS_Store
  myproject/contracts/checkViews.py
  myproject/contracts/serializers.py
  myproject/contracts/urls.py
  myproject/contracts/utils/mainPrompts.py
  myproject/contracts/utils/openAICall.py
  myproject/contracts/utils/prompts.py
Labels: 기능구현

#56 Feat/#45
  myproject/Dockerfile
  myproject/documents/tasks.py
  myproject/documents/views.py
  myproject/myproject/celery.py
  myproject/myproject/settings.py
Labels: 기능구현

#74 [Refactor/#73] 이메일 발송 대상 다수로 변경 완료
  myproject/documents/serializers.py
  myproject/documents/views.py
Labels: 기능구현, 리팩토링
